### ISSUE TITLE
setAcceleration cause wrong deceleration calculation (overshoot)

### ISSUE THREAD

**Issue by pavel-b-kr12** [gin66/FastAccelStepper#40] opened 2021-01-17 17:31 UTC
loop
{
stepper->setSpeed(variableSpeed);
//stepper->setAcceleration(9999); // uncomment this cause motor position will be over than target and motor have to go backward (same in both direction). In most bad cases it act like drunk car driver to chive target position in waves-like motion.
//stepper->setAcceleration(variableAcceleration); //same situation

long target = analogRead(A0)*5;
stepper->moveTo(target); 
}

I test on ESP32.   tested this on v0.18.11 , v0.18.02

**Comment by gin66** [comment] 2021-01-17 21:37
Sounds interesting. Could you please add a Serial.println(target) at the end and perhaps a delay(10) ? Hope you can provide the log with timestamp. This way I can try to produce it on my side.

**Comment by pavel-b-kr12** [comment] 2021-01-18 14:33
Sorry, finished project, so no hardware. This is looks like absolutely the same as overshoot examples in google. 
The code above produce NO waves but only one return, but if acceleration is low , i think waves will appear.
The output, i got with one of the settings  with waves:
Green - target, Red - current position.
![pot pos targed dif spd acc](https://user-images.githubusercontent.com/28408886/104927368-051c8680-59aa-11eb-9ed6-cc1e2f0304a2.png)

**Comment by gin66** [comment] 2021-01-18 18:31
Thanks for additional info. What is the meaning of the other three lines between 0 and 10000 ?

With this input I have tried to check on my HW (esp and avr) and could not reproduce anything close to what you get. So I have changed one of my tests to constantly issue moveTo() and setAcceleration. There has been a finding, which I have fixed, and I have added another precaution in setAcceleration. The code is uploaded to github, but not released yet.

Just I cannot explain that behavior with those changes.

Could you provide a log with timing included and your setting of speed/acceleration for the pic above ?

**Comment by pavel-b-kr12** [comment] 2021-01-18 18:58
forgot the picture above. The issue in 1st message looks like this: 
![Clipboard-2](https://user-images.githubusercontent.com/28408886/104953560-50955b80-59cf-11eb-8620-a6d3dcc0dd75.jpg)

with any code that updates setAcceleration

loop
{
stepper->setSpeed(200);
stepper->setAcceleration(9999);
stepper->moveTo(20000);
delay(10);
}

**Comment by gin66** [comment] 2021-01-18 19:55
Thanks for the code. Based on this the issue came apparent and I have added a test case to my test suite.

The issue is fixed in v0.18.12, but may reappear, if the setAcceleration() would jump back and forth between 999 and 1000. Perhaps later add a test case for this.

**Comment by gin66** [comment] 2021-01-18 19:59
added a test case with alternating acceleration: no failure

**Closed** 2021-01-20 21:21 UTC
Labels: bug
